import pytest

from phibase_pipeline.merge import (
    update_session_ids,
)


@pytest.mark.parametrize(
    'sessions,expected',
    [
        pytest.param(
            {
                'PMID:1': {
                    'phibase': {},
                    'canto': {},
                },
            },
            {
                'PMID:1': {
                    'phibase': {},
                    'canto': {},
                },
            },
            id='empty',
        ),
        pytest.param(
            {
                'PMID:1': {
                    'phibase': {
                        'genes': {
                            'Fusarium graminearum I1S474': {
                                'organism': 'Fusarium graminearum',
                                'uniquename': 'I1S474',
                            },
                        },
                        'alleles': {
                            'I1S474:0123456789abcdef-1': {
                                'allele_type': 'deletion',
                                'gene': 'Fusarium graminearum I1S474',
                                'name': 'ScOrtholog_PIG2delta',
                                'primary_identifier': 'I1S474:0123456789abcdef-1',
                                'synonyms': [],
                            },
                        },
                        'annotations': [
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': '0123456789abcdef-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': '0123456789abcdef-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_phenotype',
                                'genotype': '0123456789abcdef-genotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'GO:0000001',
                                'type': 'biological_process',
                                'gene': 'Fusarium graminearum I1S474',
                            },
                        ],
                        'genotypes': {
                            '0123456789abcdef-genotype-1': {
                                'loci': [[{'id': 'I1S474:0123456789abcdef-1'}]],
                                'organism_strain': 'PH-1',
                                'organism_taxonid': 5518,
                            }
                        },
                        'metadata': {
                            'accepted_timestamp': '2024-01-01 00:00:00',
                            'annotation_mode': 'advanced',
                            'annotation_status': 'APPROVED',
                            'annotation_status_datestamp': '2024-01-01 00:00:00',
                            'approval_in_progress_timestamp': '2024-01-01 00:00:00',
                            'approved_timestamp': '2024-01-01 00:00:00',
                            'canto_session': '0123456789abcdef',
                            'curation_accepted_date': '2024-01-01 00:00:00',
                            'curation_in_progress_timestamp': '2024-01-01 00:00:00',
                            'curation_pub_id': 'PMID:1',
                            'curator_role': 'community',
                            'first_approved_timestamp': '2024-01-01 00:00:00',
                            'has_community_curation': True,
                            'needs_approval_timestamp': '2024-01-01 00:00:00',
                            'reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_created_timestamp': '2024-01-01 00:00:00',
                            'session_first_submitted_timestamp': '2024-01-01 00:00:00',
                            'session_genes_count': 1,
                            'session_reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_term_suggestions_count': '0',
                            'session_unknown_conditions_count': '0',
                            'term_suggestion_count': '0',
                            'unknown_conditions_count': '0',
                        },
                        'metagenotypes': {
                            '0123456789abcdef-metagenotype-1': {
                                'pathogen_genotype': '0123456789abcdef-genotype-1',
                                'host_genotype': 'Triticum-aestivum-wild-type-genotype-Unknown-strain',
                                'type': 'pathogen-host',
                            }
                        },
                        'organisms': {
                            '5518': {'full_name': 'Fusarium graminearum'},
                            '4565': {'full_name': 'Triticum aestivum'},
                        },
                        'publications': {
                            'PMID:1': {},
                        },
                    },
                    'canto': {
                        'genes': {
                            'Fusarium graminearum I1S474': {
                                'organism': 'Fusarium graminearum',
                                'uniquename': 'I1S474',
                            },
                        },
                        'alleles': {
                            'I1S474:abcdef0123456789-1': {
                                'allele_type': 'deletion',
                                'gene': 'Fusarium graminearum I1S474',
                                'name': 'ScOrtholog_PIG2delta',
                                'primary_identifier': 'I1S474:abcdef0123456789-1',
                                'synonyms': [],
                            },
                        },
                        'annotations': [
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_phenotype',
                                'genotype': 'abcdef0123456789-genotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'GO:0000001',
                                'type': 'biological_process',
                                'gene': 'Fusarium graminearum I1S474',
                            },
                        ],
                        'genotypes': {
                            'abcdef0123456789-genotype-1': {
                                'loci': [[{'id': 'I1S474:abcdef0123456789-1'}]],
                                'organism_strain': 'PH-1',
                                'organism_taxonid': 5518,
                            }
                        },
                        'metadata': {
                            'accepted_timestamp': '2024-01-01 00:00:00',
                            'annotation_mode': 'advanced',
                            'annotation_status': 'APPROVED',
                            'annotation_status_datestamp': '2024-01-01 00:00:00',
                            'approval_in_progress_timestamp': '2024-01-01 00:00:00',
                            'approved_timestamp': '2024-01-01 00:00:00',
                            'canto_session': 'abcdef0123456789',
                            'curation_accepted_date': '2024-01-01 00:00:00',
                            'curation_in_progress_timestamp': '2024-01-01 00:00:00',
                            'curation_pub_id': 'PMID:1',
                            'curator_role': 'community',
                            'first_approved_timestamp': '2024-01-01 00:00:00',
                            'has_community_curation': True,
                            'needs_approval_timestamp': '2024-01-01 00:00:00',
                            'reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_created_timestamp': '2024-01-01 00:00:00',
                            'session_first_submitted_timestamp': '2024-01-01 00:00:00',
                            'session_genes_count': 1,
                            'session_reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_term_suggestions_count': '0',
                            'session_unknown_conditions_count': '0',
                            'term_suggestion_count': '0',
                            'unknown_conditions_count': '0',
                        },
                        'metagenotypes': {
                            'abcdef0123456789-metagenotype-1': {
                                'pathogen_genotype': 'abcdef0123456789-genotype-1',
                                'host_genotype': 'Triticum-aestivum-wild-type-genotype-Unknown-strain',
                                'type': 'pathogen-host',
                            }
                        },
                        'organisms': {
                            '5518': {'full_name': 'Fusarium graminearum'},
                            '4565': {'full_name': 'Triticum aestivum'},
                        },
                        'publications': {
                            'PMID:1': {},
                        },
                    },
                },
            },
            {
                'PMID:1': {
                    'phibase': {
                        'genes': {
                            'Fusarium graminearum I1S474': {
                                'organism': 'Fusarium graminearum',
                                'uniquename': 'I1S474',
                            },
                        },
                        'alleles': {
                            'I1S474:abcdef0123456789-1': {
                                'allele_type': 'deletion',
                                'gene': 'Fusarium graminearum I1S474',
                                'name': 'ScOrtholog_PIG2delta',
                                'primary_identifier': 'I1S474:abcdef0123456789-1',
                                'synonyms': [],
                            },
                        },
                        'annotations': [
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_phenotype',
                                'genotype': 'abcdef0123456789-genotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'GO:0000001',
                                'type': 'biological_process',
                                'gene': 'Fusarium graminearum I1S474',
                            },
                        ],
                        'genotypes': {
                            'abcdef0123456789-genotype-1': {
                                'loci': [[{'id': 'I1S474:abcdef0123456789-1'}]],
                                'organism_strain': 'PH-1',
                                'organism_taxonid': 5518,
                            }
                        },
                        'metadata': {
                            'accepted_timestamp': '2024-01-01 00:00:00',
                            'annotation_mode': 'advanced',
                            'annotation_status': 'APPROVED',
                            'annotation_status_datestamp': '2024-01-01 00:00:00',
                            'approval_in_progress_timestamp': '2024-01-01 00:00:00',
                            'approved_timestamp': '2024-01-01 00:00:00',
                            'canto_session': 'abcdef0123456789',
                            'curation_accepted_date': '2024-01-01 00:00:00',
                            'curation_in_progress_timestamp': '2024-01-01 00:00:00',
                            'curation_pub_id': 'PMID:1',
                            'curator_role': 'community',
                            'first_approved_timestamp': '2024-01-01 00:00:00',
                            'has_community_curation': True,
                            'needs_approval_timestamp': '2024-01-01 00:00:00',
                            'reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_created_timestamp': '2024-01-01 00:00:00',
                            'session_first_submitted_timestamp': '2024-01-01 00:00:00',
                            'session_genes_count': 1,
                            'session_reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_term_suggestions_count': '0',
                            'session_unknown_conditions_count': '0',
                            'term_suggestion_count': '0',
                            'unknown_conditions_count': '0',
                        },
                        'metagenotypes': {
                            'abcdef0123456789-metagenotype-1': {
                                'pathogen_genotype': 'abcdef0123456789-genotype-1',
                                'host_genotype': 'Triticum-aestivum-wild-type-genotype-Unknown-strain',
                                'type': 'pathogen-host',
                            }
                        },
                        'organisms': {
                            '5518': {'full_name': 'Fusarium graminearum'},
                            '4565': {'full_name': 'Triticum aestivum'},
                        },
                        'publications': {
                            'PMID:1': {},
                        },
                    },
                    'canto': {
                        'genes': {
                            'Fusarium graminearum I1S474': {
                                'organism': 'Fusarium graminearum',
                                'uniquename': 'I1S474',
                            },
                        },
                        'alleles': {
                            'I1S474:abcdef0123456789-1': {
                                'allele_type': 'deletion',
                                'gene': 'Fusarium graminearum I1S474',
                                'name': 'ScOrtholog_PIG2delta',
                                'primary_identifier': 'I1S474:abcdef0123456789-1',
                                'synonyms': [],
                            },
                        },
                        'annotations': [
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [
                                    {
                                        'rangeDisplayName': 'reduced virulence',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'PHIPO:0000015',
                                        'relation': 'infective_ability',
                                    },
                                    {
                                        'rangeDisplayName': 'flower',
                                        'rangeType': 'Ontology',
                                        'rangeValue': 'BTO:0000469',
                                        'relation': 'infects_tissue',
                                    },
                                ],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_host_interaction_phenotype',
                                'metagenotype': 'abcdef0123456789-metagenotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'PHIPO:0000001',
                                'type': 'pathogen_phenotype',
                                'genotype': 'abcdef0123456789-genotype-1',
                            },
                            {
                                'checked': 'yes',
                                'conditions': [],
                                'creation_date': '2024-01-01',
                                'evidence_code': '',
                                'extension': [],
                                'curator': {'community_curated': False},
                                'figure': '',
                                'phi4_id': ['PHI:1'],
                                'publication': 'PMID:1',
                                'status': 'new',
                                'term': 'GO:0000001',
                                'type': 'biological_process',
                                'gene': 'Fusarium graminearum I1S474',
                            },
                        ],
                        'genotypes': {
                            'abcdef0123456789-genotype-1': {
                                'loci': [[{'id': 'I1S474:abcdef0123456789-1'}]],
                                'organism_strain': 'PH-1',
                                'organism_taxonid': 5518,
                            }
                        },
                        'metadata': {
                            'accepted_timestamp': '2024-01-01 00:00:00',
                            'annotation_mode': 'advanced',
                            'annotation_status': 'APPROVED',
                            'annotation_status_datestamp': '2024-01-01 00:00:00',
                            'approval_in_progress_timestamp': '2024-01-01 00:00:00',
                            'approved_timestamp': '2024-01-01 00:00:00',
                            'canto_session': 'abcdef0123456789',
                            'curation_accepted_date': '2024-01-01 00:00:00',
                            'curation_in_progress_timestamp': '2024-01-01 00:00:00',
                            'curation_pub_id': 'PMID:1',
                            'curator_role': 'community',
                            'first_approved_timestamp': '2024-01-01 00:00:00',
                            'has_community_curation': True,
                            'needs_approval_timestamp': '2024-01-01 00:00:00',
                            'reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_created_timestamp': '2024-01-01 00:00:00',
                            'session_first_submitted_timestamp': '2024-01-01 00:00:00',
                            'session_genes_count': 1,
                            'session_reactivated_timestamp': '2024-01-01 00:00:00',
                            'session_term_suggestions_count': '0',
                            'session_unknown_conditions_count': '0',
                            'term_suggestion_count': '0',
                            'unknown_conditions_count': '0',
                        },
                        'metagenotypes': {
                            'abcdef0123456789-metagenotype-1': {
                                'pathogen_genotype': 'abcdef0123456789-genotype-1',
                                'host_genotype': 'Triticum-aestivum-wild-type-genotype-Unknown-strain',
                                'type': 'pathogen-host',
                            }
                        },
                        'organisms': {
                            '5518': {'full_name': 'Fusarium graminearum'},
                            '4565': {'full_name': 'Triticum aestivum'},
                        },
                        'publications': {
                            'PMID:1': {},
                        },
                    },
                },
            },
            id='all',
        ),
    ],
)
def test_update_session_ids(sessions, expected):
    actual = update_session_ids(sessions)
    assert expected == actual
